version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongo:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  crawler1:
    build: ./backend/
    container_name: 'crawler1'
    links:
      - mongodb
    depends_on:
      - mongodb
  
  crawler2:
    build: ./backend/
    container_name: 'crawler2'
    links:
      - mongodb
    depends_on:
      - mongodb

  crawler3:
    build: ./backend/
    container_name: 'crawler3'
    links:
      - mongodb
    depends_on:
      - mongodb
  
  web:
    build: ./frontend/
    container_name: 'crawler-front'
    ports:
      - '3000:3000'

  loadbalancer:
      build: ./load-balancer/
      container_name: 'loadbalancer'
      depends_on:
          - crawler1
          - crawler2
          - crawler3
      links:
          - web
          - crawler1
          - crawler2
          - crawler3
      ports:
          - '8080:8080'