version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    ports:
      - '27017:27017'

  crawler:
    build: ./backend/
    container_name: "crawler-back"
    ports:
      - '8888:8888'
    links:
      - mongodb
    depends_on:
      - mongodb
  
  web:
    build: ./frontend/
    container_name: 'crawler-front'
    ports:
      - '3000:3000'
    depends_on:
      - crawler